### ISSUE TITLE
minerl build出错。如何解决？

### ISSUE THREAD

**Issue by luckypoem** [neevek/minerl#1]
hi.

as3:~/minerl-site/mysite# minerl createpost --filename test1.md --format markdown --layout post --title "测试1"
Created: _pages/2014/05/13/test1.md
as3:~/minerl-site/mysite# nano _pages/2014/05/13/test1.md
as3:~/minerl-site/mysite# minerl build
Template not found: post at /usr/local/bin/minerl line 984.
as3:~/minerl-site/mysite#

how to fix it?tks

**Comment by neevek** [comment]
你指定了--layout post，表示你要用post，这个模板，但是默认是没有post模板的。默认有个default.html,你可以试试用--layout default。

**Comment by luckypoem** [comment]
hi.

搭建好了： http://mn.surmount.biz.wf/ ，不过不能设置分页的吗？我在minerl.cfg 里面没看到设置分页的地方。

**Comment by neevek** [comment]
目前不支持列表分页，但未来可能会实现。
