### ISSUE TITLE
Use HTML pages instead of Markup?

### ISSUE THREAD

**Issue by kapitaali** [neevek/minerl#2]
Hi,

this is not so much an issue as it is a question about features. I was wondering if the system could handle the _posts directory filled with HTML pages, so that the theme would be applied to the pages? I have a bunch of static HTML pages from my blog projects (that use Wordpress, so I have just the blog post body of text) that would need a system that would read the posts and apply a template, generating the site structure.

Any thoughts? Can minerl do it, or are there similar ones around? I haven't come across myself, all seem to be using Markup.

Regards,

-t

**Comment by neevek** [comment]
If you are asking about reusing existing HTML pages , then yes, you can do that. You can put all your HTML pages under `_templates` directory, then create pages, may be markdown files (since markdown support inline HTML) and reference your html files as templates, for example:

```
---
title: My page title
slug: My-page.html 
layout: My-Html-Page
format: markdown
description: some description
---
```
